PUT http://localhost:8080/api/events/11
Content-Type: application/json

{
  "title": "Concierto de Iron Maiden",
  "description": "Evento para comprobar el DTO",
  "date": "2026-09-20",
  "location": "La Floresta",
  "imageUrl": null
}